import type { DeviceProfile, PhysicalCurve } from "../../models/scenario";

export const dimmingGuideTablePoints = [
  { voltageV: 0.0, levelPct: 0, currentMa: 0, powerW: 0.0, lux1m: 0.0, lux2m: 0.0, lux3m: 0.0 },
  {
    voltageV: 1.0,
    levelPct: 10,
    currentMa: 30,
    powerW: 4.8,
    lux1m: 160.0,
    lux2m: 40.4,
    lux3m: 18.2,
  },
  {
    voltageV: 2.0,
    levelPct: 20,
    currentMa: 60,
    powerW: 9.6,
    lux1m: 320.0,
    lux2m: 80.8,
    lux3m: 36.4,
  },
  {
    voltageV: 3.0,
    levelPct: 30,
    currentMa: 90,
    powerW: 14.4,
    lux1m: 480.0,
    lux2m: 121.2,
    lux3m: 54.6,
  },
  {
    voltageV: 4.0,
    levelPct: 40,
    currentMa: 120,
    powerW: 19.2,
    lux1m: 640.0,
    lux2m: 161.6,
    lux3m: 72.8,
  },
  {
    voltageV: 5.0,
    levelPct: 50,
    currentMa: 150,
    powerW: 24.0,
    lux1m: 800.0,
    lux2m: 202.0,
    lux3m: 91.0,
  },
  {
    voltageV: 6.0,
    levelPct: 60,
    currentMa: 180,
    powerW: 28.8,
    lux1m: 960.0,
    lux2m: 242.4,
    lux3m: 109.2,
  },
  {
    voltageV: 7.0,
    levelPct: 70,
    currentMa: 210,
    powerW: 33.6,
    lux1m: 1120.0,
    lux2m: 282.8,
    lux3m: 127.4,
  },
  {
    voltageV: 8.0,
    levelPct: 80,
    currentMa: 240,
    powerW: 38.4,
    lux1m: 1280.0,
    lux2m: 323.2,
    lux3m: 145.6,
  },
  {
    voltageV: 9.0,
    levelPct: 90,
    currentMa: 270,
    powerW: 43.2,
    lux1m: 1440.0,
    lux2m: 363.6,
    lux3m: 163.8,
  },
  {
    voltageV: 10.0,
    levelPct: 100,
    currentMa: 300,
    powerW: 48.0,
    lux1m: 1600.0,
    lux2m: 404.0,
    lux3m: 182.0,
  },
] as const;

export const referenceDeviceProfiles: DeviceProfile[] = [
  {
    id: "driver-eaglerise-fms-60-350-300ma-reference",
    deviceType: "led_driver",
    manufacturer: "Eaglerise",
    model: "FMS-60-350 0-10 LD-F",
    name: "Eaglerise 60W / 300mA 0-10V Reference Driver",
    sourceReferenceId: "src-eaglerise-fms-60-350-010-revb",
    config: {
      controlType: "0-10V",
      currentMaxMa: 300,
      voltageMinVdc: 70,
      voltageMaxVdc: 200,
      currentAccuracyPct: 8,
      dimmingMinPct: 1,
      dimmingMaxPct: 100,
      standbyPowerMaxW: 0.5,
      efficiencyPct: 88,
    },
  },
  {
    id: "panel-g7-6060-48w-reference",
    deviceType: "led_panel",
    manufacturer: "G7 Lighting",
    model: "G7-PN-6060-48W-CC",
    name: "G7 600x600 48W LED Panel Optical Reference",
    sourceReferenceId: "src-g7-pn-6060-48w-cc",
    config: {
      dimensionsMm: "600x600",
      ratedPowerW: 48,
      ratedLuminousFluxLm: 5280,
      nominalCurrentMa: 300,
      centerLux1m: 1600,
      centerLux2m: 404,
      centerLux3m: 182,
    },
  },
];

export const referenceCurvesSeed: PhysicalCurve[] = [
  // Curve A: Voltage to Level %
  {
    id: "curve-010v-to-dim-level",
    deviceProfileId: "driver-eaglerise-fms-60-350-300ma-reference",
    name: "0-10V Dimmer Voltage → Level %",
    inputVariable: "dimmer_voltage_v",
    inputUnit: "V",
    outputVariable: "dim_level_pct",
    outputUnit: "%",
    interpolation: "linear",
    extrapolation: "clamp",
    status: "published",
    sourceReferenceId: "src-rnd-linear-010v-reference",
    notes: "Generic published linear 0-10V control curve (0V=0%, 10V=100%).",
    points: dimmingGuideTablePoints.map((p) => ({
      x: p.voltageV,
      y: p.levelPct,
      sourceKind: "third_party_datasheet",
      sourceReferenceId: "src-rnd-linear-010v-reference",
    })),
  },

  // Curve B: Level % to Driver Current mA
  {
    id: "curve-dim-level-to-current-ma",
    deviceProfileId: "driver-eaglerise-fms-60-350-300ma-reference",
    name: "Level % → Driver Output Current mA",
    inputVariable: "dim_level_pct",
    inputUnit: "%",
    outputVariable: "driver_current_ma",
    outputUnit: "mA",
    interpolation: "linear",
    extrapolation: "clamp",
    status: "derived",
    sourceReferenceId: "src-eaglerise-fms-60-350-010-revb",
    notes: "Derived from 300mA constant current setting anchor with linear scaling.",
    points: dimmingGuideTablePoints.map((p) => ({
      x: p.levelPct,
      y: p.currentMa,
      sourceKind: "interpolated",
      sourceReferenceId: "src-eaglerise-fms-60-350-010-revb",
    })),
  },

  // Curve C: Level % to Fixture Power W
  {
    id: "curve-dim-level-to-power-w",
    deviceProfileId: "panel-g7-6060-48w-reference",
    name: "Level % → Fixture Electrical Power W",
    inputVariable: "dim_level_pct",
    inputUnit: "%",
    outputVariable: "fixture_power_w",
    outputUnit: "W",
    interpolation: "linear",
    extrapolation: "clamp",
    status: "modelled",
    sourceReferenceId: "src-user-factory-driver-48w-300ma",
    notes: "Modeled power curve anchored at 48W full load. Not measured mains-meter data.",
    points: dimmingGuideTablePoints.map((p) => ({
      x: p.levelPct,
      y: p.powerW,
      sourceKind: "assumption",
      sourceReferenceId: "src-user-factory-driver-48w-300ma",
    })),
  },

  // Curve D1: Level % to Lux @ 1m
  {
    id: "curve-dim-level-to-lux-1m",
    deviceProfileId: "panel-g7-6060-48w-reference",
    name: "Level % → Center Illuminance @ 1m",
    inputVariable: "dim_level_pct",
    inputUnit: "%",
    outputVariable: "artificial_lux_1m",
    outputUnit: "lx",
    interpolation: "linear",
    extrapolation: "clamp",
    status: "modelled",
    sourceReferenceId: "src-g7-pn-6060-48w-cc",
    notes:
      "Anchored at published 1600 lx @ 1m full load. Intermediate points linearly interpolated.",
    points: dimmingGuideTablePoints.map((p) => ({
      x: p.levelPct,
      y: p.lux1m,
      sourceKind: "interpolated",
      sourceReferenceId: "src-g7-pn-6060-48w-cc",
    })),
  },

  // Curve D2: Level % to Lux @ 2m (Typical ceiling height ~2.7m)
  {
    id: "curve-dim-level-to-lux-2m",
    deviceProfileId: "panel-g7-6060-48w-reference",
    name: "Level % → Center Illuminance @ 2m",
    inputVariable: "dim_level_pct",
    inputUnit: "%",
    outputVariable: "artificial_lux_2m",
    outputUnit: "lx",
    interpolation: "linear",
    extrapolation: "clamp",
    status: "modelled",
    sourceReferenceId: "src-g7-pn-6060-48w-cc",
    notes: "Anchored at published 404 lx @ 2m full load.",
    points: dimmingGuideTablePoints.map((p) => ({
      x: p.levelPct,
      y: p.lux2m,
      sourceKind: "interpolated",
      sourceReferenceId: "src-g7-pn-6060-48w-cc",
    })),
  },

  // Bundled reference curve set
  {
    id: "linear-0-10v-reference-v1",
    deviceProfileId: "panel-g7-6060-48w-reference",
    name: "Mandatory Linear 0-10V Reference Table (Section 20)",
    inputVariable: "dimmer_voltage_v",
    inputUnit: "V",
    outputVariable: "fixture_power_w",
    outputUnit: "W",
    interpolation: "linear",
    extrapolation: "clamp",
    status: "modelled",
    sourceReferenceId: "src-rnd-linear-010v-reference",
    notes:
      "Authoritative section 20 simulation guide table combining 0-10V control, 300mA anchor, 48W anchor, and 1600/404/182 lx optical anchors.",
    points: dimmingGuideTablePoints.map((p) => ({
      x: p.voltageV,
      y: p.powerW,
      sourceKind: "assumption",
      sourceReferenceId: "src-rnd-linear-010v-reference",
    })),
  },

  // Legacy linear compatibility model
  {
    id: "legacy-linear-v1",
    deviceProfileId: null,
    name: "Legacy Linear Model (PLAN v1 Compatibility)",
    inputVariable: "dim_level_pct",
    inputUnit: "%",
    outputVariable: "fixture_power_w",
    outputUnit: "W",
    interpolation: "linear",
    extrapolation: "clamp",
    status: "legacy",
    sourceReferenceId: "src-legacy-linear-v1",
    notes: "Simple legacy linear proportional formula for aggregate loads.",
    points: [
      { x: 0, y: 0, sourceKind: "legacy_model" },
      { x: 100, y: 100, sourceKind: "legacy_model" },
    ],
  },
];
